apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::204583295443:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VR8NOY27CVVG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
        rolearn: arn:aws:iam::204583295443:role/UdacityFlaskDeployCBKubectlRole
        username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-29T13:50:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1514"
  uid: 264b399a-6d43-441a-8a18-8f6794d1c6ab
